import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCheckSquare,
  faLock,
  faMagnifyingGlass,
  faComment,
  faLocationPin,
  faCircleArrowRight,
  faBuildingColumns,
  faSeedling,
  faUser,
  faBars,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faCheckSquare,
  faLock,
  faMagnifyingGlass,
  faComment,
  faLocationPin,
  faCircleArrowRight,
  faBuildingColumns,
  faSeedling,
  faUser,
  faBars
);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
